name: mtenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2025.10.5
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.16.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - freetype=2.13.3
  - graphite2=1.3.13
  - harfbuzz=11.2.1
  - hdbscan=0.8.39
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.7
  - libclang13=20.1.7
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.7
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.61.2
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.3.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - scikit-learn=1.7.0
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - tzdata=2025b
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - docutils==0.22.2
      - fastjsonschema==2.21.2
      - filelock==3.18.0
      - flatbuffers==25.9.23
      - fsspec==2025.7.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.10
      - intel-cmplr-lib-ur==2025.3.0
      - intel-openmp==2025.3.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - keras==3.11.3
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - metric-learn==0.7.0
      - minisom==2.3.5
      - mkl==2025.3.0
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - namex==0.1.0
      - narwhals==2.3.0
      - nbformat==5.10.4
      - networkx==3.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - onemkl-license==2025.3.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.17.0
      - plotly==6.3.0
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.4
      - rich==14.2.0
      - rpds-py==0.27.1
      - scikit-posthocs==0.11.4
      - sentry-sdk==2.33.2
      - smmap==5.0.2
      - smote-variants==1.0.1
      - statistics==1.0.3.5
      - sympy==1.14.0
      - tbb==2022.3.0
      - tcmlib==1.4.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - torch==2.7.1
      - triton==3.3.1
      - typing-inspection==0.4.1
      - umf==1.0.2
      - urllib3==2.5.0
      - wandb==0.21.0
      - werkzeug==3.1.3
      - wrapt==2.0.0
