name: mtenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - ipykernel
  - pip
  - scikit-learn
  - umap-learn
  - pip:
      - matplotlib
      - seaborn
      - torch