name: mtenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - ipykernel
  - pip
  - scikit-learn
  - umap-learn
  - python-dotenv
  - matplotlib
  - seaborn
  - hdbscan
  - pip:
      - opencv-python==4.11.0.86
