_wandb:
    value:
        cli_version: 0.21.0
        e:
            qdwhph19bv98smpbw7ppa09abyhu2u9n:
                codePath: src/hdbscan_clustering_tuning.py
                codePathLocal: src/hdbscan_clustering_tuning.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1081101176832"
                        used: "19346563072"
                email: caitlyn.zuppinger@outlook.com
                executable: /home/czuppinger/miniconda3/envs/mtenv/bin/python3
                git:
                    commit: e5a79074610175b45d5c28ed89ab6a9387b89b8e
                    remote: https://github.com/caitzpp/VT9_Identifying-Severities-in-Osteoarthritis.git
                host: U349271
                memory:
                    total: "16616964096"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/czuppinger/repo/VT9_Identifying-Severities-in-Osteoarthritis/src/hdbscan_clustering_tuning.py
                python: CPython 3.12.11
                root: /home/czuppinger/repo/VT9_Identifying-Severities-in-Osteoarthritis
                startedAt: "2025-07-23T13:50:33.360893Z"
                writerId: qdwhph19bv98smpbw7ppa09abyhu2u9n
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.11
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
hdbscan:
    value:
        algorithm: auto
        alpha: 1
        cluster_selection_epsilon: 0
        cluster_selection_method: eom
        leaf_size: 40
        max_cluster_size: null
        metric: euclidean
        metric_params: null
        min_cluster_size: 5
        min_samples: null
        store_centers: centroid
umap:
    value:
        metric: euclidean
        min_dist: 0.1
        n_components: 2
        n_neighbors: 5
